LICENSE
Addresses Repo Mountie request PR.
https://github.com/bcgov/nr-fsa-theme/pull/5
=> Apache2.0 license

.github/workflows/release-please.yml
- test the config for the release management pipeline
=> feat: add release management pipeline

.github/workflows/semantic_pull_request.yml
- add naming convention check for pull request title refs: #17
=> feat: #17 Add naming convention check for pull request title

style-sheets/primevue-components-overrides.scss
- primevue, added custom style for font and outline button
=> feat: PrimeVue - Added custom style for font and outline button 

design-tokens/type-family.scss
- fix font face import refs: #34
=> fix: #34 Fix font face import path

package.json
changed the version from 0.0.1 to 1.0.7 in package.json
=> chore: changed the version in package.json

design-tokens/body-types.scss, design-tokens/light-buttons.scss, design-tokens/light-theme.scss, package.json, style-sheets/landing-page-components-overrides.scss, style-sheets/primevue-components-overrides.scss
- Fixing landing page button layout;
- Adding style for cards;
- Adding style for datatable;
- Minor adjustments in the primevue overrides.
=> fix: landing page button layout

style-sheets/carbon-components-overrides.scss
- Changed from px to rem
- Added new overrides
=> fix: carbon components

assets/svg/warning--filled.svg, design-tokens/body-types.scss, package.json, style-sheets/primevue-components-overrides.scss
Adjusting primevue overrides for FAM grant access pages
=> fix: Adjust some primevue component for FAM grant access pages

README.md, examples/React/example-custom.scss
Added some instructions so the package is easier to use
=> fix: improve documentation

style-sheets/carbon-components-overrides.scss
Replaced `--bcgov` with `--#{variables.$bcgov-prefix}`
=> fix: remove unnecessary override

style-sheets/primevue-components-overrides.scss
- update primevue dialog header icon to always display at top right
- regroup the dialog styles
=> fix: fix primevue dialog header icon position

style-sheets/primevue-components-overrides.scss
fixed the broken icon on the toast message
=> fix: toast broken icon

style-sheets/primevue-components-overrides.scss
Changing the unit from px to rem to be more responsive
=> fix: switching from px to rem unit

style-sheets/primevue-components-overrides.scss
cleaning up primevue stylesheet:
- removed FAM specific style change
- some auto formatting
=> fix: cleanup primevue stylesheet

style-sheets/landing-page-components-overrides.scss
Removed the unused type import in landing page stylesheet as we now do font update in each application
=> fix: removed the type import in landing page stylesheet

style-sheets/primevue-components-overrides.scss
- updated the styling on the data table, paginator and dropdown for the new design for FAM ticket [849](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/849)
=> feat: primevue - adjust pagination style for data table and some extra

style-sheets/primevue-components-overrides.scss
- styling for the primevue card style.
https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/846
=> feat: primevue - card styling

style-sheets/primevue-components-overrides.scss
- change the button border effect on focus condition
=> fix: primevue button style on focus condition

style-sheets/carbon-components-overrides.scss, style-sheets/primevue-components-overrides.scss
- Changed the color of the labels for both Carbon and PrimeVue
=> feat: changing labels color

style-sheets/primevue-components-overrides.scss
- fix primevue button on focus effect to add important
- fix primevue input text height
- fix primevue inputtext on focus border
=> fix: fix primevue button on focus effect to add important

style-sheets/carbon-components-overrides.scss
- Fixed identifier to make sure the style gets applied.
=> fix: change identifiers for the style rule

style-sheets/primevue-components-overrides.scss
- Styling for primevue sidebar
- some responsive design for mobile and tablet
=> fix: sidebar and some responsive styling

style-sheets/primevue-components-overrides.scss
- Adding style for error notification messages;
- Adding style for warning notification messages;
- Fixing icon color for success notification messages;
=> feat: adding style for error and warning notification messages

style-sheets/primevue-components-overrides.scss
- refactored of sidebar media query to work better.
=> fix: primevue sidebar media query refactor

style-sheets/primevue-components-overrides.scss
- primevue component general styling
=> feat: primevue breadcrumb component styling

style-sheets/primevue-components-overrides.scss
Adding styling for the secondary button, which was missing.
=> feat: adding secondary button styling

style-sheets/primevue-components-overrides.scss
- primevue step component general stylings
=> feat: steps primevue component

style-sheets/primevue-components-overrides.scss
- fixed the bottom of the step text being cut.
=> fix: step component text partially hidden

style-sheets/primevue-components-overrides.scss
- added styles for the current route on primevue breadcrumb.
=> fix: primevue breadcrum styling for current route

style-sheets/primevue-components-overrides.scss
- fixed styling on broken wrapping for the notification message
=> fix: notification message primevue componente wrapping

style-sheets/primevue-components-overrides.scss
- small style fix for sortable icon
=> fix(primevue): datatable component sortable icon

style-sheets/primevue-components-overrides.scss
- Changed the margin on the breadcrumb
=> fix(primevue): breadcrumb component spacing

style-sheets/primevue-components-overrides.scss
- remove important, which is not needed
- adjust the classname selection
=> fix: primevue dialog button style

style-sheets/primevue-components-overrides.scss
- fixed white space, text sizing and button alignment
=> fix(primevue): design on confirm pop up

style-sheets/primevue-components-overrides.scss
=> fix(primevue): removing tab style when focus

style-sheets/primevue-components-overrides.scss
fixed conflicting styling on confirm dialog and dialog component
=> fix(primevue): dialog styling
